module "agilis_prod" {
  source = "../../"

  subscription_id                      = var.subscription_id
  tenant_id                            = var.tenant_id
  environment                          = var.environment
  location                             = var.location
  common_prefix                        = var.common_prefix
  tags                                 = var.tags
  log_analytics_retention_in_days      = var.log_analytics_retention_in_days
  archive_after_days                   = var.archive_after_days
  app_service_sku_name                 = var.app_service_sku_name
  app_service_always_on                = var.app_service_always_on
  app_service_name_suffix              = var.app_service_name_suffix
  cosmos_mongo_database_max_throughput = var.cosmos_mongo_database_max_throughput
  cosmos_free_tier_enabled             = var.cosmos_free_tier_enabled
  cosmos_enable_automatic_failover     = var.cosmos_enable_automatic_failover
  cosmos_account_name_suffix           = var.cosmos_account_name_suffix
  storage_account_replication_type     = var.storage_account_replication_type
  storage_account_tier                 = var.storage_account_tier
  storage_container_names              = var.storage_container_names
  key_vault_sku_name                   = var.key_vault_sku_name
  key_vault_soft_delete_retention_days = var.key_vault_soft_delete_retention_days
  key_vault_purge_protection_enabled  = var.key_vault_purge_protection_enabled
  key_vault_additional_rbac_assignments = var.key_vault_additional_rbac_assignments
  terraform_principal_id               = var.terraform_principal_id
  bastion_enabled                      = var.bastion_enabled
  bastion_subnet_cidr                  = var.bastion_subnet_cidr
  bastion_vm_subnet_cidr               = var.bastion_vm_subnet_cidr
  bastion_vm_size                      = var.bastion_vm_size
  bastion_vm_admin_username            = var.bastion_vm_admin_username
  bastion_vm_admin_password            = var.bastion_vm_admin_password
  bastion_auto_shutdown_enabled        = var.bastion_auto_shutdown_enabled
  bastion_auto_shutdown_time           = var.bastion_auto_shutdown_time
  bastion_auto_shutdown_timezone       = var.bastion_auto_shutdown_timezone
}
